### ISSUE TITLE
准实时处理时的疑惑

### ISSUE THREAD

**Issue by lanlan-lanlan-lanlan** [DingdongD/SIMFNet#3]
在用matlab控制dca1000进行数据的传输与存储时，每次都必须等bin文件完全生成才能进行下一次采集，而每次bin文件的生成都会导致2-3s的延时，多次采集的时间叠加起来时延就很大了，这样似乎就不能称为“准实时处理”了，您对这个问题怎么看？请问您有遇到这样的问题吗？

**Comment by DingdongD** [comment]
如果您看过我的准实时系统处理的话，您会发现我们在处理bin文件时并不是等到完全生成再进行下一次采集，而是在采集过程中通过上位机如MATLAB不断地去抓取包，bin文件每次都会按照一定的量回传数据，我们抓到包后就对这部分数据进行处理，处理完以后再进行包的下一部分处理，来形成一个抓包和计算处理的准并行过程，总体上而言参数控制合理的话完整抓包时间为2s左右；但在数据量过大的时候时延确实会比较大。可能你们可以尝试一下CLI这套方法。

**Comment by lanlan-lanlan-lanlan** [comment]
好的，谢谢，我去试试
