### ISSUE TITLE
实时系统实现bug

### ISSUE THREAD

**Issue by Zhenyu98** [DingdongD/SIMFNet#4]
作者你好，

我目前正在使用此仓库中的数据采集程序`CaptureData.m`，该程序持续监控本地 生成`.bin` 文件并实时读取、处理数据。然而，我遇到了一个问题：**数据文件大小的 `path_size` 变量突然变化的**，而不是按预期逐步增加。

像这种
![1716889208974](https://github.com/DingdongD/SIMFNet/assets/62387006/b8da5655-4df0-4fd0-a4b7-a645fc97f624)
`path_size` 的这种突然变化导致程序无法在实时系统中正常运行，因为它不能平稳地过渡到预期大小，这也影响了 `RealTimeRun` 脚本的实时功能。

请问您是否能提供一些见解或解决方案，以便在数据写入 `.bin` 文件时，`path_size` 能够平稳递增？

感谢您的帮助。

镇宇

**Comment by DingdongD** [comment]
是存在这种情况的，但是没关系，处理的时候会按这个增量去处理
